import { Application } from "@/types/Application";
import { ApplicationStatus } from "@/enums/ApplicationStatus";

export const mockApplications: Application[] = [
  {
    studentId: "MAN221001",
    fullName: "Alizzz bin Abu",
    email: "ali@graduate.utm.my",
    applicationStatus: ApplicationStatus.APPROVED,
    studentFaculty: "RAZAK FACULTY",
    programCode: "MANPA1CKA",
    programName: "MASTER OF SOFTWARE ENGINEERING",
  },
  {
    studentId: "MAN221002",
    fullName: "Bakar bin Bakhtiar",
    email: "bakar@graduatezzz.utm.my",
    applicationStatus: ApplicationStatus.REJECTED,
    studentFaculty: "RAZAK FACULTY",
    programCode: "MANPA1CKA",
    programName: "MASTER OF SOFTWARE ENGINEERING",
  },
  {
    studentId: "MAN221003",
    fullName: "Changzzz Chen",
    email: "chang@gzzzraduate.utm.my",
    applicationStatus: ApplicationStatus.APPROVED,
    studentFaculty: "RAZAK FACULTY",
    programCode: "MANPA1CKA",
    programName: "MASTER OF SOFTWARE ENGINEERING",
  },
  {
    studentId: "MAN221004",
    fullName: "Faiz bin Farid",
    email: "faiz@graduate.utm.my",
    applicationStatus: ApplicationStatus.PENDING,
    studentFaculty: "RAZAK FACULTY",
    programCode: "MANPA1CKA",
    programName: "MASTER OF SOFTWARE ENGINEERING",
  },
  {
    studentId: "MAN221005",
    fullName: "Darwich bin Daud",
    email: "darwich@graduate.utm.my",
    applicationStatus: ApplicationStatus.PENDING,
    studentFaculty: "RAZAK FACULTY",
    programCode: "MANPA1CKA",
    programName: "MASTER OF SOFTWARE ENGINEERING",
  },
  {
    studentId: "MAN221006",
    fullName: "Graham Bell",
    email: "graham@graduate.utm.my",
    applicationStatus: ApplicationStatus.PENDING,
    studentFaculty: "RAZAK FACULTY",
    programCode: "MANPA1CKA",
    programName: "MASTER OF SOFTWARE ENGINEERING",
  },
  {
    studentId: "MAN221007",
    fullName: "Haniffah binti Hanifa",
    email: "haniffah@graduate.utm.my",
    applicationStatus: ApplicationStatus.PENDING,
    studentFaculty: "RAZAK FACULTY",
    programCode: "MANPA1CKA",
    programName: "MASTER OF SOFTWARE ENGINEERING",
  },
  {
    studentId: "MAN221008",
    fullName: "Jauhari bin Manikam",
    email: "jauhari@graduate.utm.my",
    applicationStatus: ApplicationStatus.PENDING,
    studentFaculty: "RAZAK FACULTY",
    programCode: "MANPA1CKA",
    programName: "MASTER OF SOFTWARE ENGINEERING",
  },
  {
    studentId: "MAN221009",
    fullName: "Kelvin Celcius",
    email: "kelvin@graduate.utm.my",
    applicationStatus: ApplicationStatus.PENDING,
    studentFaculty: "RAZAK FACULTY",
    programCode: "MANPA1CKA",
    programName: "MASTER OF SOFTWARE ENGINEERING",
  },
  {
    studentId: "MAN221010",
    fullName: "Lew Lau",
    email: "lew@graduate.utm.my",
    applicationStatus: ApplicationStatus.PENDING,
    studentFaculty: "RAZAK FACULTY",
    programCode: "MANPA1CKA",
    programName: "MASTER OF SOFTWARE ENGINEERING",
  },
  {
    studentId: "MAN221011",
    fullName: "Muthusamy Sivaraju",
    email: "muthusamy@graduate.utm.my",
    applicationStatus: ApplicationStatus.PENDING,
    studentFaculty: "RAZAK FACULTY",
    programCode: "MANPA1CKA",
    programName: "MASTER OF SOFTWARE ENGINEERING",
  },
  {
    studentId: "MAN221012",
    fullName: "Nur Nami binti Nun",
    email: "nurnami@graduate.utm.my",
    applicationStatus: ApplicationStatus.PENDING,
    studentFaculty: "RAZAK FACULTY",
    programCode: "MANPA1CKA",
    programName: "MASTER OF SOFTWARE ENGINEERING",
  },
  {
    studentId: "MAN221013",
    fullName: "Oren bin Jingga",
    email: "oren@graduate.utm.my",
    applicationStatus: ApplicationStatus.PENDING,
    studentFaculty: "RAZAK FACULTY",
    programCode: "MANPA1CKA",
    programName: "MASTER OF SOFTWARE ENGINEERING",
  },
  {
    studentId: "MAN221014",
    fullName: "Padparascha Papadom",
    email: "padparascha@graduate.utm.my",
    applicationStatus: ApplicationStatus.PENDING,
    studentFaculty: "RAZAK FACULTY",
    programCode: "MANPA1CKA",
    programName: "MASTER OF SOFTWARE ENGINEERING",
  },
  {
    studentId: "MAN221015",
    fullName: "Zeus Zhang",
    email: "zeus@graduate.utm.my",
    applicationStatus: ApplicationStatus.PENDING,
    studentFaculty: "RAZAK FACULTY",
    programCode: "MANPA1CKA",
    programName: "MASTER OF SOFTWARE ENGINEERING",
  },
];
