// import { Application } from "@/types/Application";
// import { ApplicationStatus } from "@/enums/ApplicationStatus";
//
// export const mockApplications: Application[] = [
//   {
//     studentId: "MAN221001",
//     fullName: "Ali bin Abu",
//     email: "ali@graduate.utm.my",
//     applicationStatus: ApplicationStatus.REJECTED,
//     studentFaculty: "RAZAK FACULTY",
//     programCode: "MANPA1CKA",
//     programName: "MASTER OF SOFTWARE ENGINEERING",
//     dateSubmitted: "12/12/2023",
//     semester: "Semester 1 - 2023/2024 ",
//   },
//   {
//     studentId: "MAN221001",
//     fullName: "Ali bin Abu",
//     email: "ali@graduate.utm.my",
//     applicationStatus: ApplicationStatus.APPROVED,
//     studentFaculty: "RAZAK FACULTY",
//     programCode: "MANPA1CKA",
//     programName: "MASTER OF SOFTWARE ENGINEERING",
//     dateSubmitted: "21/11/2023",
//     semester: "Semester 1 - 2022/2023 ",
//   },
//   {
//     studentId: "MAN221001",
//     fullName: "Ali bin Abu",
//     email: "ali@graduate.utm.my",
//     applicationStatus: ApplicationStatus.APPROVED,
//     studentFaculty: "RAZAK FACULTY",
//     programCode: "MANPA1CKA",
//     programName: "MASTER OF SOFTWARE ENGINEERING",
//     dateSubmitted: "6/2/2023",
//     semester: "Semester 2 - 2022/2023 ",
//   },
//   {
//     studentId: "MAN221001",
//     fullName: "Ali bin Abu",
//     email: "ali@graduate.utm.my",
//     applicationStatus: ApplicationStatus.APPROVED,
//     studentFaculty: "RAZAK FACULTY",
//     programCode: "MANPA1CKA",
//     programName: "MASTER OF SOFTWARE ENGINEERING",
//     dateSubmitted: "8/1/2023",
//     semester: "Semester 1 - 2023/2024 ",
//   },
//   {
//     studentId: "MAN221001",
//     fullName: "Ali bin Abu",
//     email: "ali@graduate.utm.my",
//     applicationStatus: ApplicationStatus.PENDING,
//     studentFaculty: "RAZAK FACULTY",
//     programCode: "MANPA1CKA",
//     programName: "MASTER OF SOFTWARE ENGINEERING",
//     dateSubmitted: "11/6/2024",
//     semester: "Semester 2 - 2023/2024 ",
//   },
// ];
